// <auto-generated />
using System;
using DSSStudentRisk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSSStudentRisk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309072909_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DSSStudentRisk.Models.AHPCriteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AttendanceWeight")
                        .HasColumnType("double");

                    b.Property<double>("Attendance_Study")
                        .HasColumnType("double");

                    b.Property<double>("ConsistencyRatio")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("StudyWeight")
                        .HasColumnType("double");

                    b.Property<double>("TestWeight")
                        .HasColumnType("double");

                    b.Property<double>("Test_Attendance")
                        .HasColumnType("double");

                    b.Property<double>("Test_Study")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("AHPCriteria");
                });

            modelBuilder.Entity("DSSStudentRisk.Models.RiskResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("longtext");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiskResults");
                });

            modelBuilder.Entity("DSSStudentRisk.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DSSStudentRisk.Models.StudentPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Attendance")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("StudyHours")
                        .HasColumnType("double");

                    b.Property<double>("TestScore")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("StudentPerformances");
                });
#pragma warning restore 612, 618
        }
    }
}
